print('                (            )')
print('               (         )')
print('              (      )')
print('             (____)')
print('             /AAAA\\')
print('            /AAAAAA\\')
print('           /AAAAAAAA\\')
print('          /AAAAAAAAAA\\')
print('         /AAAAAAAAAAAA\\')
print('        /AAAAAAAAAAAAAA\\')
print('       /AAAAAAAAAAAAAAAA\\')
print('      /AAAAAAAAAAAAAAAAAA\\')
    
